### ISSUE TITLE
SSH確立後のAnsible化

### ISSUE THREAD

**Issue by Akidsuki** [tk07Sky/setup_scripts#1]
先人の財産や各OSごとの対応をしやすくするために、SSH確立後はAnsibleでの構築にしませんか？

**Comment by tk07Sky** [comment]
@Akidsuki 
なるほどー、それもいいかもね。
ただAnsibleについてあんまり知らないので、教えてもらいつつ、になりそう…

**Comment by Akidsuki** [comment]
多分やらないと思うのでクローズ
